# ______________________________________________________________________________
# Data Generating Process based on Belloni et al. (2017) with modified CATE
# ______________________________________________________________________________

library(tidyverse)
library(MASS)

#' Generate Synthetic Data (Belloni et al. 2017 modified)
#'
#' @param n Number of observations to generate.
#' @param p Number of predictors.
#' @param Rd2 Value for \exp{R^2_d \in \{0, .1, .2, .3, .4, .5, .6, .7, .8, .9\}}.
#' @param Ry2 Value for \exp{R^2_y \in \{0, .1, .2, .3, .4, .5, .6, .7, .8, .9\}}.
#' @param rho Value for controlling the correlation between predictors, i.e.,
#'  value of \exp{\rho} in \exp{\Sigma_{kj} = (\rho)^{|j-k|}}. Default to 0.5.
#' @param seed If provided, seed to use for pseudo-random generation.
#'
#' @returns A list containing the generated simulation data and ground truth parameters:
#' * `y`: Numeric vector of observed outcomes \exp{Y_i}.
#' * `m_0`: Numeric vector of true propensity scores \exp{m_0(X_i) = \Pr(D_i=1 \mid X_i)}.
#' * `d`: Integer vector of binary treatment indicators \exp{D_i \in \{0, 1\}}.
#' * `X`: Numeric matrix of size n x p containing covariate values.
#' * `nu`: Numeric vector of independent standard uniform draws \exp{\nu_i \sim \mathcal{U}(0,1)} used for treatment assignment.
#' * `zeta`: Numeric vector of outcome regression noise draws \exp{\zeta_i \sim \mathcal{N}(0,1)}.
#' * `theta0`: Numeric vector of length p containing the sparse sequence coefficients \exp{\theta_{0,j} = 1/j^2}.
#' * `Sigma`: Covariance matrix of size p x p with entry \exp{\Sigma_{jk} = \rho^{|j-k|}}.
#' * `cd`: Numeric scaling constant \exp{c_d} derived from \exp{R^2_d}.
#' * `cy`: Numeric scaling constant \exp{c_y} derived from \exp{R^2_y}.
#' * `Rd2`: Numeric value specifying the input \exp{R^2_d}.
#' * `Ry2`: Numeric value specifying the input \exp{R^2_y}.
#' * `rho`: Numeric auto-regressive parameter \exp{\rho} for the covariate covariance matrix.
#' * `quad`: Numeric scalar representing the quadratic form \exp{Q = \theta_0^\top \Sigma \theta_0}.
#' * `ate_true`: Numeric value of the sample-average true treatment effect \exp{\widehat{\text{ATE}}_{\text{true}} = \frac{1}{n} \sum_{i=1}^n \tau(X_i)}.
#' * `gate_true`: Numeric vector of true Group Average Treatment Effects (GATEs) averaged across quantile-based bins of \exp{X_1}.
#'
#' @references
#' Belloni, A., Chernozhukov, V., Fernandez-Val, I., and Hansen, C. (2017):
#' "Supplement to 'Program Evaluation and Causal Inference With High-Dimensional
#' Data'," Econometrica Supplemental Material, 85,
#' http://dx.doi.org/10.3982/ECTA12723.
#'
#' @md
#'
gen_data_belloni <- function(n = 1000,
                             p = 250,
                             Rd2 = 0.5,
                             Ry2 = 0.5,
                             rho = 0.5,
                             seed = NULL) {

  if (!is.null(seed)) set.seed(seed)

  # Covariance matrix Sigma_{jk} = rho^{|j-k|}
  idx <- 1:p
  Sigma <- rho^abs(outer(idx, idx, "-"))

  # Sparse coefficient vector theta0_j = (1/j)^2
  theta0 <- matrix((1 / idx)^2, ncol = 1)

  # Draw covariates X ~ N(0, Sigma)
  X <- MASS::mvrnorm(n = n, mu = rep(0, p), Sigma = Sigma)

  # Scaling constants
  quad <- as.numeric(t(theta0) %*% Sigma %*% theta0)

  cd <- if (Rd2 == 0) 0 else sqrt(((pi^2 / 3) * Rd2) / ((1 - Rd2) * quad))
  cy <- if (Ry2 == 0) 0 else sqrt((Ry2) / ((1 - Ry2) * quad))

  # Treatment assignment (Propensity score)
  beta_d <- cd * theta0
  lin_d  <- as.numeric(X %*% beta_d)
  p_d    <- 1 / (1 + exp(-lin_d)) # True logistic probability
  nu     <- runif(n)
  d      <- as.integer(p_d > nu)

  # Outcome generation (Modified for CATE on X1)
  beta_y <- cy * theta0
  tau_X  <- as.numeric(X[, 1] * beta_y[1])  # Treatment effect depends ONLY on X1
  g_X    <- as.numeric(X %*% beta_y)        # Main outcome signal
  zeta   <- rnorm(n)

  y <- g_X + d * tau_X + zeta

  # Quantile-based GATE bins on X1
  max_grid <- 5
  grid <- as.numeric(quantile(X[, 1], probs = (0:max_grid) / max_grid, na.rm = TRUE))
  g_bin <- findInterval(X[, 1], vec = grid, rightmost.closed = TRUE, all.inside = TRUE)

  gate_sums   <- rowsum(tau_X, g_bin, reorder = TRUE)
  gate_counts <- rowsum(rep(1, length(tau_X)), g_bin, reorder = TRUE)
  gate_true   <- as.numeric(gate_sums / gate_counts)

  list(
    y = y,
    m_0 = p_d,
    d = d,
    X = X,
    tau_X = tau_X,
    g_X = g_X,
    ate_true = mean(tau_X),
    gate_true = gate_true,
    gate_bins = g_bin
  )
}

#' Format Belloni Data to Tibble
#'
#' Converts the raw list output from \code{\link{gen_data_belloni}} into a formatted
#' tibble ready for downstream modeling.
#'
#' @param x A list generated by \code{\link{gen_data_belloni}}.
#'
#' @returns A tibble containing:
#' * `y`: Numeric vector of observed outcomes.
#' * `d`: Integer vector of binary treatment indicators (0 or 1).
#' * `X1, X2, ...`: Numeric covariate columns named sequentially from `X1` up to `Xp`.
#'
#' @examples
#' data_list <- gen_data_belloni(n = 100, p = 10)
#' dt <- format_data_belloni(data_list)
#' dt
#'
#' @md
format_data_belloni <- function(x) {
  X <- as_tibble(x$X)
  colnames(X) <- paste0("X", 1:ncol(X))
  bind_cols(tibble(y = x$y, d = x$d, p_true = x$m_0, .name_repair = "unique"), X)
}
